[project]
name = "eam-suite"
version = "0.1.0"
description = "This is a set of scripts and an example CSV file created by @neetintel on X who manages www.hfgcs.com."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
